# Install Submariner broker (runs in a dedicated management cluster or namespace)
subctl deploy-broker \
  --kubeconfig /path/to/management-kubeconfig \
  --globalnet                   # Enable global CIDR management for overlapping pod CIDRs

# Join AWS cluster to Submariner
subctl join \
  --kubeconfig /path/to/aws-cluster-kubeconfig \
  --clusterid aws-production-euw1 \
  broker-info.subm              # Generated by deploy-broker

# Join GCP cluster to Submariner
subctl join \
  --kubeconfig /path/to/gcp-cluster-kubeconfig \
  --clusterid gcp-production-euw1 \
  broker-info.subm

# Verify cross-cluster connectivity
subctl verify \
  --kubeconfig1 /path/to/aws-cluster-kubeconfig \
  --kubeconfig2 /path/to/gcp-cluster-kubeconfig \
  --verbose
